lista = ["juan", "Ivan", "Adrian", "Jair"]
print(lista)
print(lista[2])
lista.append("Alexa")
print(lista)
lista.insert(1, "javier")
print(lista)
lista.remove("juan")
print(lista)
lista.pop(1)
print(lista)